development:
  secret_key_base: df4941e22796fac2458f93729b3f95680aecc74e6a6fcc5ba0b3714ebbeb2a7099acb714a33b7de87bcd8e2b75ad04c624856a496649c42b33e336071a5f6aa3
  #mandrill_smtp_address: smtp.mandrillapp.com
  #mandrill_smtp_port: 587
  #mandrill_smtp_domain: trackdons.local
  #mandrill_smtp_username: alvaro+trackdons@furilo.com
  #mandrill_smtp_password: cT-fKy2ktA04rRmxAGeJaQ
  mandrill_smtp_address: smtp.mandrillapp.com
  mandrill_smtp_port: 587
  mandrill_smtp_domain: trackdons.org
  mandrill_smtp_username: alvaro+trackdons@furilo.com
  mandrill_smtp_password: afLpXaRKZBHpNuIWHc_LaQ

test:
  secret_key_base: 074ecf44262876b32f0547beaff25b9f165719f11191392026335cef9488b3e67600ce476e3060fb57c48d5797fa9fb8e1629ea434fb09e21520cba8f1974c8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mandrill_smtp_address: smtp.mandrillapp.com
  mandrill_smtp_port: 587
  mandrill_smtp_domain: trackdons.org
  mandrill_smtp_username: alvaro+trackdons@furilo.com
  mandrill_smtp_password: afLpXaRKZBHpNuIWHc_LaQ
  